

import Navegador from "./nav/nav";
import "./globals.css";
import Footer from "./footer/Footer";
import Mapa from "./utlis/Google";

export const metadata = {
  title: "Meu app",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {




  return (
    <html lang="pt-br">
      <head>
        {/* Adicionando Google Fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap"
          rel="stylesheet"
        />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />


        <link rel="preconnect" href="https://fonts.googleapis.com" />
        {/* <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin /> */}
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&display=swap" rel="stylesheet" />

      </head>

      <body

      >
        <Navegador />
        {children}

        {/* <Mapa/> */}
        <Footer />
      </body>
    </html>
  );
}
